justfile
ssz_rs/Cargo.toml
ssz_rs/examples/serde.rs
ssz_rs/src/bitlist.rs
ssz_rs/src/bitvector.rs
ssz_rs/src/lib.rs
ssz_rs/src/list.rs
ssz_rs/src/serde_test.rs
ssz_rs/src/uint.rs
ssz_rs/src/vector.rs

Adds `serde` impls for custom types

Add serde feature

---

ssz-rs-derive/src/lib.rs

the `SimpleSerialize` derive proc-macro supports the "new type" rust pattern, e.g.
```rust
#[derive(SimpleSerialize)]
struct LocalType(ssz_rs::SomeType)
// specialize behavior of `ssz_rs::SomeType` via `impl LocalType`
```
@realbigsean found a bug where the generated ser/de code treated this "new type" wrapper as a SSZ container of one element, instead of treating it "transparently" (see rust's `repr(transparent)` or serde's `serde(transparent)` attributes for the idea)
this PR fixes the bug by, in fact, serde'ing transparently

fix bug when serializing a "newtype" SSZ wrapper

---

ssz-rs/src/ser.rs

fix: avoid overflow on 32 bit architectures

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/array.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/boolean.rs
ssz-rs/src/de.rs
ssz-rs/src/error.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/ser.rs
ssz-rs/src/uint.rs
ssz-rs/src/union.rs
ssz-rs/src/vector.rs

error refactor

---

ssz-rs/src/uint.rs

required for parsing data from the engine API

impl `U256::from_hex`

---

README.md
justfile
rust-toolchain.toml
ssz-rs/Cargo.toml

Release: v0.8

---

README.md
ssz-rs-test-gen/src/main.rs
ssz-rs/examples/container_with_some_types.rs
ssz-rs/examples/serde.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/de.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/serde.rs
ssz-rs/src/vector.rs
ssz-rs/tests/bitlist.rs
ssz-rs/tests/bitvector.rs
ssz-rs/tests/containers.rs

Common trait impls

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/ser.rs

simplify some of the serialization routines

---

.github/workflows/rust.yml
.gitignore
README.md

@ralexstokes to finish this PR the ssz-rs repo would need the [CodeCov app to be added](https://docs.codecov.com/docs#prerequisites).

Adds code coverage workflow and badge.

---

ssz-rs/src/array.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/boolean.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/uint.rs
ssz-rs/src/vector.rs

in the process of refactoring trait hierarchy to support "opt-in" Merkleization
also reorg some `serde` code

clean up `Merkleized` trait

---

ssz-rs-derive/README.md

add some docs on what the proc macro provides

---

.github/workflows/ci.yml

a recent update broke the current ci settings

use corrct version of parameter in CI

---

ssz-rs/src/lib.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/multiproofs/generalized_index.rs
ssz-rs/src/merkleization/multiproofs/mod.rs

implements basic verification logic for single and multi proofs using generalized indices
TODO:
FUTURE:
implement type-safe generalized index paths to generalized index
implement proving code to generate proofs in first place

implement multiproofs

---

ssz-rs-derive/src/lib.rs
ssz-rs/examples/generalized_indices.rs
ssz-rs/src/array.rs
ssz-rs/src/boolean.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/multiproofs/generalized_index.rs
ssz-rs/src/merkleization/multiproofs/mod.rs
ssz-rs/src/uint.rs
ssz-rs/src/vector.rs

implement computation of generalized indices

---

.github/workflows/ci.yml
ssz-rs/src/lib.rs
ssz-rs/src/merkleization/multiproofs/generalized_index.rs

Replaces `log_2` logic with `checked_ilog2`

---

ssz-rs-derive/src/lib.rs
ssz-rs/examples/generalized_indices.rs
ssz-rs/src/array.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/boolean.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/generalized_index.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/node.rs
ssz-rs/src/uint.rs
ssz-rs/src/union.rs
ssz-rs/src/vector.rs

update name of generalized index trait and add support for unions

---

.github/workflows/ci.yml
justfile
ssz-rs-derive/src/lib.rs
ssz-rs/src/array.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/boolean.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/generalized_index.rs
ssz-rs/src/merkleization/merkleize.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/multiproofs.rs
ssz-rs/src/merkleization/node.rs
ssz-rs/src/merkleization/proofs.rs
ssz-rs/src/uint.rs
ssz-rs/src/vector.rs

implement `Prove` trait for single proof case

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/merkleize.rs
ssz-rs/src/merkleization/proofs.rs
ssz-rs/src/union.rs

impl `Prove` for  unions

---

ssz-rs/src/container.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/proofs.rs
ssz-rs/src/union.rs

support proofs of "decoration" for ssz types that have it

---

ssz-rs/src/lib.rs
ssz-rs/src/merkleization/proofs.rs

Tidy interface

---

rust-toolchain.toml
ssz-rs/Cargo.toml
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/list.rs

Update MSRV and alloy-primitives
