ssz_rs/examples/another_container.rs
ssz_rs/examples/container_with_some_types.rs
ssz_rs/scripts/README.md
ssz_rs/scripts/gen.py
ssz_rs/src/array.rs
ssz_rs/src/bitlist.rs
ssz_rs/src/bitvector.rs
ssz_rs/src/boolean.rs
ssz_rs/src/list.rs
ssz_rs/src/merkleization/cache.rs
ssz_rs/src/merkleization/mod.rs
ssz_rs/src/uint.rs
ssz_rs/src/union.rs
ssz_rs/src/vector.rs
ssz_rs/tests/basic_vector.rs
ssz_rs/tests/bitlist.rs
ssz_rs/tests/bitvector.rs
ssz_rs/tests/boolean.rs
ssz_rs/tests/containers.rs
ssz_rs/tests/test_utils.rs
ssz_rs/tests/uints.rs
ssz_rs_derive/src/lib.rs

First of several PRs to add caching / merkle-backing for some SSZ types:
This PR adds some basic infrastructure and installs a "non-caching" merkle backing for the following types:
- Vectors
- Lists
Other types have relatively small Merkle trees in common usage so we can skip caching for now.
The intent here is to provide a Merkle backing for quick production of (multi)proofs along with caching to avoid expensive recomputation of hash tree root.
NOTE: there are also some other ergonomics improvements in this PR around mutating / manipulating Lists and Vectors so that the caching abstraction is sound.

Cache merkleization for some types

---

ssz_rs/Cargo.toml
ssz_rs/examples/another_container.rs
ssz_rs/examples/container_with_some_types.rs
ssz_rs/src/array.rs
ssz_rs/src/bitlist.rs
ssz_rs/src/bitvector.rs
ssz_rs/src/boolean.rs
ssz_rs/src/list.rs
ssz_rs/src/merkleization/mod.rs
ssz_rs/src/uint.rs
ssz_rs/src/union.rs
ssz_rs/src/vector.rs
ssz_rs/tests/test_utils.rs
ssz_rs_derive/src/lib.rs

after working through some of the early caching work in #3, it looks like an "intrusive" caching design makes the most sense and because of this, the `Context` type removed in this PR does not pull its own weight...
the only "service" it was providing was a static set of "zero" hashes that can be inlined as global statics using the `lazy_static` crate commonly used for this purpose across the rust ecosystem.

deprecate Merkle `Context` in lieu of static data

---

ssz-rs/src/de.rs
ssz-rs/src/error.rs
ssz-rs/src/lib.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/node.rs
ssz-rs/src/ser.rs

Adds some missing docs and some examples in the top-level module documentation. I am not entirely sure on what an "instance" is, so I did not explain much in the docs for that - is it a value?

docs: add examples and crate docs

---

codecov.yml

Looks like coverage is [over 70% for `ssz-rs`](https://app.codecov.io/gh/ralexstokes/ssz-rs) (see the per-directory breakdown at the bottom of the page), so ignoring these directories will give us a clearer picture of coverage in PRs & the CodeCov UI.
@ralexstokes This will override the [global yaml](https://docs.codecov.com/docs/codecov-yaml#global-yaml), but only for the keys mentioned in `codecov.yml`.

Ignore ssz-rs-derive & ssz-rs-test-gen for coverage

---

ssz-rs/src/merkleization/node.rs

while `Node` represents a hash itself, it would be useful for `Node` to implement `Hash`. for example, there are multiple instances in the ethereum consensus spec where we would like to key by the [`Root`](https://github.com/ralexstokes/ethereum-consensus/blob/46ca1716f2b1651e59b8a565b5bbcadf6b052fa5/src/primitives.rs#L8) of some data structure.

feat: derive Hash for merkle node

---

ssz-rs/Cargo.toml
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/serde.rs
ssz-rs/src/vector.rs

when `serde` feature is enabled in a `no_std` build, it fails due to the references to `std`. This PR makes `serde` feature compatible with `no_std`.
Note that `thiserror` is completely removed because it doesn't support `no_std`.

Make `no_std` build work with `serde` feature enabled

---

ssz-rs/src/lib.rs

should be non-substantive and cleans up the code a bit

refactor exports to skip duplication in `lib.rs`

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/array.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/ser.rs
ssz-rs/src/vector.rs

minor but also skips a redundant iteration over the variable lengths summation that can be done inline like the fixed lengths summation

harden typing to increase safety of serialization routine

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/union.rs

discovered in the Oak Security audit
> Excess bytes in the encoding of None do not trigger errors

error on extra input when deserializing `Union[None]` for some SSZ union type

---

ssz-rs/src/de.rs
ssz-rs/src/list.rs

from Oak Security audit:
> When deserializing Array, List, and Vector objects, depending on whether they are fixed or variable, one of two functions is called within deserialize_homogeneous_composite - deserialize_variable_homogeneous_composite or deserialize_fixed_homogeneous_composite.
The latter is called when the type is fixed, and the corresponding deserialize functions have already validated the length of the object to be a multiple of the default value of that type obtained using T::size_hint. An example for the Array type is the validation performed in ssz-rs/src/array.rs:51-65.
Nevertheless, the deserialize_fixed_homogeneous_composite function in lines 71-78 validates whether the modulo of the length of the deserialized object and the default size for its type is different from …

skip some duplicate checks when deserializing fixed types

---

ssz-rs-derive/src/lib.rs

from the Oak Security audit:
> SimpleSerialize trait implements the derive function, which performs some actions on the passed input. One of them is input.data validation, carried out at ssz-rs-derive/src/lib.rs:548.
This function, depending on whether the validation is successful, has the option of returning ValidationState::Validated, or executing plain panic! when it turns out that the data is incorrect.
Consequently, after this action, there is no technical possibility that the state of input.data will still be Unvalidated. This means that the validation performed in ssz-rs-derive/src/lib.rs:550-553 is redundant.

simplify proc macro validation

---

ssz-rs/Cargo.toml

remove unnecessary `dep:` prefix for `ssz-rs` feature set

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/array.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/boolean.rs
ssz-rs/src/de.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/ser.rs
ssz-rs/src/uint.rs
ssz-rs/src/union.rs
ssz-rs/src/utils.rs
ssz-rs/src/vector.rs

following up on #92 -- there is desire to separate the merkleization capability from the ser/de capability for SSZ types
previously, all of these capabilities where coupled under the `SimpleSerialize` trait.
now, the ser/de stuff has been split into a `Serializable` trait and `SimpleSerialize` simply requires that along w/ the merkle trait `Merkleized`
while doing this refactor, it became clear that the `Sized` trait could be bundled and it doesn't really make much sense on it's own
beyond that, there are various refactors to limit the scope of traits required to their bare minimum.
this should support future proc macro work that allows a user to choose just the serde and forgo the merkle functionality

refactor ser/de into `Serializable` trait without merkle caps

---

ssz-rs-derive/src/lib.rs
ssz-rs/src/de.rs
ssz-rs/src/lib.rs

Right now, the `SimpleSerialize` proc macro will allocate a `Default::default()` instance when deserializing and then set each field accordingly.
We can save some space by parsing the input to get all relevant spans (along w/ validating invariants of the data) and then making an instance of the type once after we know where to segment the incoming encoding for each field.
This PR implements this change.

Avoid allocating default container when deserializing

---

ssz-rs/src/list.rs
ssz-rs/src/vector.rs

the `index_mut` implementation should also support index types other than `usize` to support batch editing operations ("copy N bytes into these N bytes of the source")
the existing implementation restricted the index type to just `usize` so that this information could be used to inform caching strategies
this PR relaxes the constraint for now, with the caveat that we will likely need to constrain the implementation a bit so we can actually get the indexing data during a call to `index_mut` (e.g. only allow `index_mut` for `usize` and the `Range` family of index types) so we can concretely get the actual indexes mutated

use more permissive index type for {Vector, List}::index_mut

---

ssz-rs-derive/Cargo.toml
ssz-rs-derive/README.md
ssz-rs-derive/src/lib.rs
ssz-rs-derive/tests/mod.rs

only supports `derive(Merkleize)` for now, as it would require brute force strategy for deserialize...

add support for `transparent` mode of derive operation

---

ssz-rs/Cargo.toml
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/serde.rs
ssz-rs/src/uint.rs
ssz-rs/src/vector.rs

Fixes #110 
This change should fix the bug surfaced in #110. It also simplifies the `serde` implementation across the crate by using the `serde` `derive` macros where possible

Simplify `serde` impl

---

ssz-rs/Cargo.toml
ssz-rs/examples/another_container.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/mod.rs
ssz-rs/src/merkleization/node.rs
ssz-rs/src/serde.rs
ssz-rs/src/utils.rs
ssz-rs/src/vector.rs

simplify trait impls to expose a "bytes-like" thing 
normalize `fmt` impls for hex-printing

clean up implementation of `Node`

---

ssz-rs-derive/src/lib.rs
ssz-rs-derive/tests/mod.rs
ssz-rs/src/de.rs

this simple does a "brute force" approach to deserializing a `transparent` derived type
otherwise, we would need to extend the `Deserialize` trait with some kind of `DeserializeSeed` function (following serde's approach)

extend `transparent` proc macro attr behavior to Serialize and Deserialize

---

ssz-rs/Cargo.toml

Bump version up to 0.5. Needed because the reth stack uses `^0.5` so updates to `mev-rs` leveraging `reth` crates are not possible due to versioning conflicts in `ethereum-consensus`. After this is merged the `ssz-rs` dependency in `ethereum-consesus` can be pumped to latest which should resolve the conflicts?

Bump alloy dependency

---

ssz-rs-derive/src/lib.rs
ssz-rs/examples/generalized_indices.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/lib.rs
ssz-rs/src/merkleization/multiproofs/mod.rs
ssz-rs/src/merkleization/node.rs
ssz-rs/tests/test_utils.rs

main thing is a bug fix on container computation
adds `Indexed` on `Node` (required upstream)
and some convenience `impls` to make `PathElements` from more basic rust types
note: exposes an unimplemented `Indexed` impl on `Bit{list,vector}`, will follow up in a future PR with these features

More work on generalized indices

---

ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/vector.rs

Originally, the mutable APIs into the underlying type that `List` and `Vector` wrap were specialized to the local wrapping types so that mutations could be tracked along the way to support caching a la #17.
I'd like to release a v1 of this library and won't have caching support so go ahead and drop the specialized implementations here, in lieu of just exposing the full functionality of the wrapped types.

Remove methods that reimplement underlying functionality of `List` and `Vector`

---

ssz-rs-derive/src/lib.rs
ssz-rs-derive/tests/mod.rs
ssz-rs/src/merkleization/generalized_index.rs

Fixes and extensions for the derive proc macro

---

.github/workflows/ci.yml
justfile
ssz-rs-derive/src/lib.rs
ssz-rs-derive/tests/mod.rs
ssz-rs-test-gen/src/main.rs
ssz-rs/examples/another_container.rs
ssz-rs/examples/container_with_some_types.rs
ssz-rs/examples/proofs.rs
ssz-rs/src/array.rs
ssz-rs/src/bitlist.rs
ssz-rs/src/bitvector.rs
ssz-rs/src/boolean.rs
ssz-rs/src/container.rs
ssz-rs/src/lib.rs
ssz-rs/src/list.rs
ssz-rs/src/merkleization/merkleize.rs
ssz-rs/src/merkleization/node.rs
ssz-rs/src/merkleization/proofs.rs
ssz-rs/src/uint.rs
ssz-rs/src/union.rs
ssz-rs/src/vector.rs
ssz-rs/tests/basic_vector.rs
ssz-rs/tests/bitlist.rs
ssz-rs/tests/bitvector.rs
ssz-rs/tests/boolean.rs
ssz-rs/tests/containers.rs
ssz-rs/tests/test_utils.rs
ssz-rs/tests/uints.rs

this was originally left `mut` to facilitate caching of the Merkle tree,
but given it is a big ask in Rust, let's drop it and make the resulting
simplifications

refactor: drop `mut` on `HashTreeRoot::hash_tree_root`

---

ssz-rs/Cargo.toml
ssz-rs/src/merkleization/proofs.rs

This PR implements a feature for enabling the `asm` feature on the `sha2` crate. When testing against a real world payload (generate a proof of transaction inclusion against the transactions root), these are the numbers:
- `sha2-asm` feature disabled:
```
Transactions root: 0x3834068daa909f5553bd06299dc60ccd43fa2c24da3778dda30b6c7fc767f240, num transactions: 129
Index to prove: 26
Generated proof in 855.763416ms
Verified proof in 9.708µs
```
- `sha2-asm` feature enabled:
```
Transactions root: 0x3834068daa909f5553bd06299dc60ccd43fa2c24da3778dda30b6c7fc767f240, num transactions: 129
Index to prove: 26
Generated proof in 133.917375ms
Verified proof in 1.917µs
```
With `sha2-asm` enabled, proof generation becomes around 6,5 times faster.

`sha2-asm` feature
